version: 2
project_name: cm

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.BuildTime={{.Date}}
    binary: cm

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    wrap_in_directory: true

brews:
  - repository:
      owner: rehrumesh
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/rehrumesh/cm"
    description: "Container monitor - stream Docker compose logs with a beautiful TUI"
    license: "MIT"
    install: |
      bin.install "cm"
    test: |
      system "#{bin}/cm", "--version"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: rehrumesh
    name: cm
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
